# Generated by Django 4.0 on 2024-12-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalBidPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(max_length=50, verbose_name='Material')),
                ('bid_price', models.FloatField(verbose_name='Bid Price')),
            ],
            options={
                'verbose_name': 'MetalBidPrice',
                'verbose_name_plural': 'MetalBidPrices',
            },
        ),
    ]
