# Generated by Django 4.0 on 2025-01-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metalbidprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmePriceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Entry Date')),
                ('data_source', models.CharField(max_length=50, verbose_name='Data Source')),
                ('material', models.CharField(max_length=50, verbose_name='Material')),
                ('bid_price', models.FloatField(verbose_name='Bid Price')),
                ('ask_price', models.FloatField(verbose_name='Ask Price')),
                ('currency', models.CharField(max_length=50, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LmePriceTrend',
                'verbose_name_plural': 'LmePriceTrends',
            },
        ),
    ]
